name: latihanpraktikum4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/pecalsemanggi.png
  - assets/sotolamongan.jpeg
  - assets/gadogado.jpeg
  - assets/baksomalang.jpeg
  - assets/tahucampur.png
  - assets/rawon.jpeg
  - assets/rujakcingur.jpeg
  - assets/sateponorogo.jpeg
  - assets/tahutek.jpeg
  - assets/lontongbalap.jpeg
  - assets/rujaksotobanyuwangi.jpeg
  - assets/sateklopo.jpeg
